# Étape 1 : image de Node.js
FROM node:18-alpine

WORKDIR /app

# Copier les fichiers package.json et tsconfig pour l'installation des dépendances
COPY package*.json ./
COPY tsconfig*.json ./

# Installer toutes les dépendances, y compris les devDependencies
RUN npm install

# Copier le code source dans le conteneur
COPY . .

# Exposer le port 3000 pour l'application NestJS
EXPOSE 3000

# Lancer l'application en mode développement avec nodemon
CMD ["npm", "run", "start:dev"]
